<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-05-07T22:19:12+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Manila',
];
