<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-05-07T23:28:22+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.5',
    'version_db_installed' => '20201116182100',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1620397148,
    ],
];
