<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-05-07T22:05:46+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Joseph Local API',
        ],
    ],
];
